// 天体の表示上の重要度。運動の kind(恒星/惑星/衛星)が「中心天体が何か」という
// 力学上の分類であるのに対し、こちらは「マップで既定でも見せるか、絞り込みの対象にするか」
// という編集上の判断で、同じ kind: 'planet' の中から準惑星・小天体を分ける。
// メッシュ構築(THREE 依存)と分けてあるのは、可視性の規則を DOM もレンダラも無しに
// 評価できるようにするため。
import { SolarSystemId } from '../../physics/solar-system/solar-system';
import { BodyClass } from './celestial-entity-def';

export { BodyClass, bodyClassOfKind } from './celestial-entity-def';

// 現実の太陽系の各天体の重要度。天体を登録すると Record の網羅性検査がここを要求する。
const BODY_CLASS_BY_ID: Record<SolarSystemId, BodyClass> = {
  sun: 'star',
  mercury: 'planet',
  venus: 'planet',
  earth: 'planet',
  mars: 'planet',
  jupiter: 'planet',
  saturn: 'planet',
  uranus: 'planet',
  neptune: 'planet',
  moon: 'satellite',
  phobos: 'satellite',
  deimos: 'satellite',
  metis: 'satellite',
  adrastea: 'satellite',
  amalthea: 'satellite',
  thebe: 'satellite',
  io: 'satellite',
  europa: 'satellite',
  ganymede: 'satellite',
  callisto: 'satellite',
  himalia: 'satellite',
  elara: 'satellite',
  ananke: 'satellite',
  carme: 'satellite',
  pasiphae: 'satellite',
  sinope: 'satellite',
  pan: 'satellite',
  daphnis: 'satellite',
  prometheus: 'satellite',
  pandora: 'satellite',
  epimetheus: 'satellite',
  janus: 'satellite',
  mimas: 'satellite',
  enceladus: 'satellite',
  tethys: 'satellite',
  dione: 'satellite',
  rhea: 'satellite',
  titan: 'satellite',
  hyperion: 'satellite',
  iapetus: 'satellite',
  phoebe: 'satellite',
  triton: 'satellite',
  nereid: 'satellite',
  puck: 'satellite',
  miranda: 'satellite',
  ariel: 'satellite',
  umbriel: 'satellite',
  titania: 'satellite',
  oberon: 'satellite',
  ceres: 'dwarf',
  pluto: 'dwarf',
  charon: 'satellite',
  styx: 'satellite',
  nix: 'satellite',
  kerberos: 'satellite',
  hydra: 'satellite',
  haumea: 'dwarf',
  hiiaka: 'satellite',
  namaka: 'satellite',
  makemake: 'dwarf',
  eris: 'dwarf',
  dysnomia: 'satellite',
  vesta: 'smallBody',
  pallas: 'smallBody',
  halley: 'smallBody',
  encke: 'smallBody',
  sedna: 'dwarf',
  quaoar: 'dwarf',
  weywot: 'satellite',
  chariklo: 'smallBody',
  hygiea: 'smallBody',
  eros: 'smallBody',
  ryugu: 'smallBody',
  bennu: 'smallBody',
  orcus: 'dwarf',
  vanth: 'satellite',
  gonggong: 'dwarf',
  salacia: 'dwarf',
  varuna: 'dwarf',
  ixion: 'dwarf',
  arrokoth: 'smallBody',
  chiron: 'smallBody',
  interamnia: 'smallBody',
  europa52: 'smallBody',
  davida: 'smallBody',
  juno: 'smallBody',
  psyche: 'smallBody',
  eunomia: 'smallBody',
  sylvia: 'smallBody',
  apophis: 'smallBody',
  didymos: 'smallBody',
  tempel1: 'smallBody',
  wild2: 'smallBody',
  hartley2: 'smallBody',
  cruithne: 'smallBody',
  kamooalewa: 'smallBody',
  tk7: 'smallBody',
  eureka: 'smallBody',
};

// 現実の太陽系の天体の表示クラス。
export function solarSystemBodyClass(id: SolarSystemId): BodyClass {
  return BODY_CLASS_BY_ID[id];
}
