// 物理関数の回帰テスト エントリポイント。
// `npm run test:physics` から tsconfig.test.json でコンパイル後、これを node 実行する。
import { runAll } from './harness';
import { register as registerVec3 } from './vec3.test';
import { register as registerKinematicState } from './kinematic-state.test';
import { register as registerElements } from './elements.test';
import { register as registerAttitude } from './attitude.test';
import { register as registerTimeStep } from './time-step.test';
import { register as registerSweptSphere } from './swept-sphere.test';
import { register as registerAtmosphere } from './atmosphere.test';
import { register as registerEphemeris } from './ephemeris.test';
import { register as registerShadow } from './shadow.test';
import { register as registerSrp } from './srp.test';
import { register as registerAttractor } from './attractor.test';
import { register as registerOcclusion } from './occlusion.test';
import { register as registerBodyOrientation } from './body-orientation.test';
import { register as registerKeplerOrbit } from './kepler-orbit.test';
import { register as registerSatelliteOrbit } from './satellite-orbit.test';
import { register as registerProjection } from './projection.test';
import { register as registerDynamics } from './dynamics.test';
import { register as registerFrame } from './frame.test';
import { register as registerDeque } from './deque.test';
import { register as registerStateQueue } from './state-queue.test';
import { register as registerDynamicTrajectory } from './dynamic-trajectory.test';
import { register as registerHalo } from './halo.test';
import { register as registerPlan } from './plan.test';
import { register as registerHudLayout } from './hud-layout.test';
import { register as registerShortcutHint } from './shortcut-hint.test';
import { register as registerBodyVisibility } from './body-visibility.test';
import { register as registerAsteroidBelt } from './asteroid-belt.test';
import { register as registerTrajectoryFeatures } from './trajectory-features.test';
import { register as registerNBody } from './n-body.test';
import { register as registerShape } from './shape.test';
import './creative-placement-validation.test';

registerVec3();
registerKinematicState();
registerElements();
registerAttitude();
registerTimeStep();
registerSweptSphere();
registerAtmosphere();
registerEphemeris();
registerShadow();
registerSrp();
registerAttractor();
registerOcclusion();
registerBodyOrientation();
registerKeplerOrbit();
registerSatelliteOrbit();
registerProjection();
registerDynamics();
registerFrame();
registerDeque();
registerStateQueue();
registerDynamicTrajectory();
registerHalo();
registerPlan();
registerHudLayout();
registerBodyVisibility();
registerShortcutHint();
registerTrajectoryFeatures();
registerAsteroidBelt();
registerNBody();
registerShape();

runAll();
