// 物理関数の回帰テスト エントリポイント。
// `npm run test:physics` から tsconfig.test.json でコンパイル後、これを node 実行する。
import { runAll } from './harness';
import { register as registerVec3 } from './vec3.test';
import { register as registerKinematicState } from './kinematic-state.test';
import { register as registerElements } from './elements.test';
import { register as registerAttitude } from './attitude.test';
import { register as registerTimeStep } from './time-step.test';
import { register as registerSphereContact } from './sphere-contact.test';
import { register as registerCollisionResponse } from './collision-response.test';
import { register as registerSurfaceContact } from './surface-contact.test';
import { register as registerContact } from './contact.test';
import { register as registerAtmosphere } from './atmosphere.test';
import { register as registerEphemeris } from './ephemeris.test';
import { register as registerShadow } from './shadow.test';
import { register as registerSrp } from './srp.test';
import { register as registerCelestialBody } from './celestial-body.test';
import { register as registerSolarSystem } from './solar-system.test';
import { register as registerFrameAnchors } from './frame-anchors.test';
import { register as registerFocusTarget } from './focus-target.test';
import { register as registerOcclusion } from './occlusion.test';
import { register as registerBodyOrientation } from './body-orientation.test';
import { register as registerKeplerOrbit } from './kepler-orbit.test';
import { register as registerSatelliteOrbit } from './satellite-orbit.test';
import { register as registerProjection } from './projection.test';
import { register as registerDynamics } from './dynamics.test';
import { register as registerFrame } from './frame.test';
import { register as registerDeque } from './deque.test';
import { register as registerSpatialGrid } from './spatial-grid.test';
import { register as registerMaxHeap } from './max-heap.test';
import { register as registerStateQueue } from './state-queue.test';
import { register as registerDynamicTrajectory } from './dynamic-trajectory.test';
import { register as registerKeplerExtrapolation } from './kepler-extrapolation.test';
import { register as registerHalo } from './halo.test';
import { register as registerCollinearAnalytic } from './collinear-analytic.test';
import { register as registerOrbitCatalog } from './orbit-catalog.test';
import { register as registerPlan } from './plan.test';
import { register as registerHudLayout } from './hud-layout.test';
import { register as registerMapScale } from './map-scale.test';
import { register as registerShortcutHint } from './shortcut-hint.test';
import { register as registerBodyVisibility } from './body-visibility.test';
import { register as registerPointField } from './point-field.test';
import { register as registerTrajectoryFeatures } from './trajectory-features.test';
import { register as registerNBody } from './n-body.test';
import { register as registerShape } from './shape.test';
import { register as registerIrregularSatellites } from './irregular-satellites.test';
import { register as registerLaplaceSatellites } from './laplace-satellites.test';
import { register as registerSmallBodies } from './small-bodies.test';
import { register as registerEquatorialSatellites } from './equatorial-satellites.test';
import { register as registerEphemerisProfile } from './ephemeris-profile.test';
import { register as registerAbsoluteEphemeris } from './absolute-ephemeris.test';
import { register as registerAstronomicalTime } from './astronomical-time.test';
import { register as registerEphemerisPackFormat } from './ephemeris-pack-format.test';
import { register as registerChebyshevEphemeris } from './chebyshev-ephemeris.test';
import { register as registerPackedAbsoluteEphemeris } from './packed-absolute-ephemeris.test';
import { register as registerSaveEphemerisContext } from './save-ephemeris-context.test';
import { register as registerOptimize } from './optimize.test';
import { register as registerPredictedArc } from './predicted-arc.test';
import { register as registerSurfaceCandidates } from './surface-candidates.test';
import { register as registerThermal } from './thermal.test';
import { register as registerBlackbody } from './blackbody.test';
import { register as registerWindowAgreement } from './window-agreement.test';
import { register as registerPlanArcRange } from './plan-arc-range.test';
import './creative-placement-validation.test';
import { register as registerProtein } from './protein-combat-state.test';
import { register as registerProteinFormation } from './protein-formation.test';
import { register as registerProjectileOrientation } from './projectile-orientation.test';
import { register as registerProteinRibbonCollision } from './protein-ribbon-collision.test';
import { register as registerProteinRibbonGeometry } from './protein-ribbon-geometry.test';
import { register as registerProteinBrownianMotion } from './protein-brownian-motion.test';
import { register as registerProteinMotionController } from './protein-motion-controller.test';
import { register as registerProteinRenderBindings } from './protein-render-bindings.test';
import { register as registerGameEntityDispose } from './game-entity-dispose.test';
import { register as registerBoosterStack } from './booster-stack.test';
import { register as registerBoosterSeparation } from './booster-separation.test';
import { register as registerZeroVelocity } from './zero-velocity.test';

registerVec3();
registerKinematicState();
registerElements();
registerAttitude();
registerTimeStep();
registerSphereContact();
registerCollisionResponse();
registerSurfaceContact();
registerContact();
registerAtmosphere();
registerEphemeris();
registerShadow();
registerSrp();
registerCelestialBody();
registerSolarSystem();
registerFrameAnchors();
registerFocusTarget();
registerOcclusion();
registerBodyOrientation();
registerKeplerOrbit();
registerSatelliteOrbit();
registerProjection();
registerDynamics();
registerFrame();
registerDeque();
registerSpatialGrid();
registerMaxHeap();
registerStateQueue();
registerDynamicTrajectory();
registerKeplerExtrapolation();
registerHalo();
registerCollinearAnalytic();
registerOrbitCatalog();
registerPlan();
registerHudLayout();
registerMapScale();
registerBodyVisibility();
registerShortcutHint();
registerTrajectoryFeatures();
registerPointField();
registerNBody();
registerShape();
registerIrregularSatellites();
registerLaplaceSatellites();
registerSmallBodies();
registerEquatorialSatellites();
registerEphemerisProfile();
registerAbsoluteEphemeris();
registerAstronomicalTime();
registerEphemerisPackFormat();
registerChebyshevEphemeris();
registerPackedAbsoluteEphemeris();
registerSaveEphemerisContext();
registerOptimize();
registerPredictedArc();
registerSurfaceCandidates();
registerThermal();
registerBlackbody();
registerWindowAgreement();
registerPlanArcRange();
registerProtein();
registerProteinFormation();
registerProjectileOrientation();
registerProteinRibbonCollision();
registerProteinRibbonGeometry();
registerProteinBrownianMotion();
registerProteinMotionController();
registerProteinRenderBindings();
registerGameEntityDispose();
registerBoosterStack();
registerBoosterSeparation();
registerZeroVelocity();

runAll().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
