// 物理関数の回帰テスト エントリポイント。
// `npm run test:physics` から tsconfig.test.json でコンパイル後、これを node 実行する。
import { runAll } from './harness';
import { register as registerVec3 } from './vec3.test';
import { register as registerKinematicState } from './kinematic-state.test';
import { register as registerElements } from './elements.test';
import { register as registerAttitude } from './attitude.test';
import { register as registerAttitudeControl } from './attitude-control.test';
import { register as registerTimeStep } from './time-step.test';
import { register as registerSphereContact } from './sphere-contact.test';
import { register as registerCapsuleContact } from './capsule-contact.test';
import { register as registerCollisionResponse } from './collision-response.test';
import { register as registerAtmosphere } from './atmosphere.test';
import { register as registerEphemeris } from './ephemeris.test';
import { register as registerShadow } from './shadow.test';
import { register as registerSrp } from './srp.test';
import { register as registerAttractor } from './attractor.test';
import { register as registerOcclusion } from './occlusion.test';
import { register as registerBodyOrientation } from './body-orientation.test';
import { register as registerKeplerOrbit } from './kepler-orbit.test';
import { register as registerSatelliteOrbit } from './satellite-orbit.test';
import { register as registerProjection } from './projection.test';
import { register as registerDynamics } from './dynamics.test';
import { register as registerFrame } from './frame.test';
import { register as registerDeque } from './deque.test';
import { register as registerSpatialGrid } from './spatial-grid.test';
import { register as registerStateQueue } from './state-queue.test';
import { register as registerDynamicTrajectory } from './dynamic-trajectory.test';
import { register as registerKeplerExtrapolation } from './kepler-extrapolation.test';
import { register as registerHalo } from './halo.test';
import { register as registerPlan } from './plan.test';
import { register as registerPlanExecutorMath } from './plan-executor-math.test';
import { register as registerPlanExecutor } from './plan-executor.test';
import { register as registerHudLayout } from './hud-layout.test';
import { register as registerMapScale } from './map-scale.test';
import { register as registerShortcutHint } from './shortcut-hint.test';
import { register as registerBodyVisibility } from './body-visibility.test';
import { register as registerPointField } from './point-field.test';
import { register as registerTrajectoryFeatures } from './trajectory-features.test';
import { register as registerNBody } from './n-body.test';
import { register as registerShape } from './shape.test';
import { register as registerIrregularSatellites } from './irregular-satellites.test';
import { register as registerLaplaceSatellites } from './laplace-satellites.test';
import { register as registerSmallBodies } from './small-bodies.test';
import { register as registerEquatorialSatellites } from './equatorial-satellites.test';
import { register as registerEphemerisProfile } from './ephemeris-profile.test';
import { register as registerAbsoluteEphemeris } from './absolute-ephemeris.test';
import { register as registerAstronomicalTime } from './astronomical-time.test';
import { register as registerEphemerisPackFormat } from './ephemeris-pack-format.test';
import { register as registerChebyshevEphemeris } from './chebyshev-ephemeris.test';
import { register as registerPackedAbsoluteEphemeris } from './packed-absolute-ephemeris.test';
import { register as registerSaveEphemerisContext } from './save-ephemeris-context.test';
import { register as registerGeometry } from './geometry.test';
import { register as registerOptimize } from './optimize.test';
import { register as registerSectionMoments } from './section-moments.test';
import { register as registerHullLoft } from './hull-loft.test';
import { register as registerInertiaTensor } from './inertia-tensor.test';
import { register as registerAerodynamics } from './aerodynamics.test';
import { register as registerGravityGradient } from './gravity-gradient.test';
import { register as registerGeomagnetic } from './geomagnetic.test';
import { register as registerTsiolkovsky } from './tsiolkovsky.test';
import { register as registerThrustAlignment } from './thrust-alignment.test';
import './creative-placement-validation.test';

registerVec3();
registerKinematicState();
registerElements();
registerAttitude();
registerAttitudeControl();
registerTimeStep();
registerSphereContact();
registerCapsuleContact();
registerCollisionResponse();
registerAtmosphere();
registerEphemeris();
registerShadow();
registerSrp();
registerAttractor();
registerOcclusion();
registerBodyOrientation();
registerKeplerOrbit();
registerSatelliteOrbit();
registerProjection();
registerDynamics();
registerFrame();
registerDeque();
registerSpatialGrid();
registerStateQueue();
registerDynamicTrajectory();
registerKeplerExtrapolation();
registerHalo();
registerPlan();
registerPlanExecutorMath();
registerPlanExecutor();
registerHudLayout();
registerMapScale();
registerBodyVisibility();
registerShortcutHint();
registerTrajectoryFeatures();
registerPointField();
registerNBody();
registerShape();
registerIrregularSatellites();
registerLaplaceSatellites();
registerSmallBodies();
registerEquatorialSatellites();
registerEphemerisProfile();
registerAbsoluteEphemeris();
registerAstronomicalTime();
registerEphemerisPackFormat();
registerChebyshevEphemeris();
registerPackedAbsoluteEphemeris();
registerSaveEphemerisContext();
registerGeometry();
registerOptimize();
registerSectionMoments();
registerHullLoft();
registerInertiaTensor();
registerAerodynamics();
registerGravityGradient();
registerGeomagnetic();
registerTsiolkovsky();
registerThrustAlignment();

runAll().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
