/**
 * Version 1 of the Tepui ephemeris pack format.
 *
 * The file is deliberately small and boring so it can be generated by a
 * dependency-free Node tool and consumed in a browser:
 *
 *   0..7    ASCII magic "TEPUIEPK"
 *   8..9    uint16 LE major version (1)
 *   10..11  uint16 LE minor version (0)
 *   12..15  uint32 LE header size (32)
 *   16..19  uint32 LE canonical manifest UTF-8 byte length
 *   20..23  uint32 LE payload byte length
 *   24..31  zero-filled reserved bytes
 *   ...     canonical JSON manifest, UTF-8
 *   ...     contiguous Float64 position coefficients, little endian
 *
 * A series stores X, then Y, then Z Chebyshev coefficients.  Thus a series
 * of degree n has 3 * (n + 1) Float64 values.  The manifest's
 * coefficientOffset is measured in Float64 values, not bytes.  Coefficients
 * are evaluated on each series' [start, end] interval with the usual affine
 * mapping to [-1, 1].  Times and positions are in the units declared by the
 * manifest. Version 1 uses barycentric ICRF/J2000 positions in metres and
 * times expressed as seconds from the J2000 ET epoch on the TDB scale.
 *
 * The manifest is canonical JSON: object keys are sorted recursively, arrays
 * retain their order, and no insignificant whitespace is emitted.  The
 * payloadSha256 field, when present, is the lowercase SHA-256 digest of only
 * the payload bytes (not the header or manifest).  The browser-side format
 * code intentionally does not depend on a crypto implementation; the Node
 * CLI verifies this field.
 */

import type { ChebyshevEphemerisPack } from './types';

export const EPHEMERIS_PACK_MAGIC = 'TEPUIEPK';
export const EPHEMERIS_PACK_FORMAT = 'tepui-ephemeris-pack';
export const EPHEMERIS_PACK_VERSION = 1;
export const EPHEMERIS_PACK_MINOR_VERSION = 0;
export const EPHEMERIS_PACK_HEADER_BYTES = 32;

export interface EphemerisSeries {
  readonly body: string;
  readonly start: number;
  readonly end: number;
  readonly degree: number;
  readonly coefficientOffset: number;
  readonly coefficientCount: number;
}

export interface EphemerisManifest {
  readonly format: typeof EPHEMERIS_PACK_FORMAT;
  readonly version: typeof EPHEMERIS_PACK_VERSION;
  readonly frame: 'ICRF-J2000';
  readonly timeScale: 'TDB';
  /** validStart/end and series start/end are seconds from J2000 ET. */
  readonly timeOrigin: 'J2000-ET';
  readonly positionUnit: 'm';
  readonly timeUnit: 's';
  readonly validStart: number;
  readonly validEnd: number;
  readonly series: readonly EphemerisSeries[];
  readonly payloadSha256?: string;
  readonly [key: string]: unknown;
}

export type EphemerisManifestBase = Omit<EphemerisManifest, 'series'>;

export interface ChebyshevSegmentInput {
  readonly body: string;
  readonly start: number;
  readonly end: number;
  /** [x coefficients, y coefficients, z coefficients]. */
  readonly coefficients: readonly [readonly number[], readonly number[], readonly number[]];
}

export interface DecodedEphemerisPack {
  readonly manifest: EphemerisManifest;
  readonly payload: Float64Array;
  /** The exact bytes hashed by manifest.payloadSha256. */
  readonly payloadBytes: Uint8Array;
  readonly manifestJson: string;
}

/** Evaluator view with the canonical absolute-ephemeris metadata spelling. */
export type CanonicalEvaluatorEphemerisPack = Omit<ChebyshevEphemerisPack, 'manifest'> & {
  readonly manifest: Omit<ChebyshevEphemerisPack['manifest'], 'coordinateFrame' | 'timeScale'> & {
    readonly coordinateFrame: 'ICRF-J2000';
    readonly timeScale: 'TDB';
  };
};

export class EphemerisPackFormatError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = 'EphemerisPackFormatError';
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function requireString(value: unknown, field: string): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new EphemerisPackFormatError(`${field} must be a non-empty string`);
  }
  return value;
}

function requireFiniteNumber(value: unknown, field: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new EphemerisPackFormatError(`${field} must be finite`);
  }
  return value;
}

function requireNonNegativeInteger(value: unknown, field: string): number {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) {
    throw new EphemerisPackFormatError(`${field} must be a non-negative safe integer`);
  }
  return value;
}

/** Sort object keys recursively while preserving array order. */
export function canonicalJson(value: unknown): string {
  if (value === null || typeof value === 'boolean' || typeof value === 'string' || typeof value === 'number') {
    if (typeof value === 'number' && !Number.isFinite(value)) {
      throw new EphemerisPackFormatError('manifest cannot contain a non-finite number');
    }
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalJson(item)).join(',')}]`;
  }
  if (!isRecord(value)) {
    throw new EphemerisPackFormatError('manifest contains an unsupported JSON value');
  }
  const keys = Object.keys(value).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`;
}

/** Validate and return the manifest with its public shape narrowed. */
export function validateManifest(value: unknown): EphemerisManifest {
  if (!isRecord(value)) throw new EphemerisPackFormatError('manifest must be a JSON object');
  if (value.format !== EPHEMERIS_PACK_FORMAT) {
    throw new EphemerisPackFormatError(`unsupported manifest format: ${String(value.format)}`);
  }
  if (value.version !== EPHEMERIS_PACK_VERSION) {
    throw new EphemerisPackFormatError(`unsupported manifest version: ${String(value.version)}`);
  }
  if (value.frame !== 'ICRF-J2000') throw new EphemerisPackFormatError('frame must be ICRF-J2000');
  if (value.timeScale !== 'TDB') throw new EphemerisPackFormatError('timeScale must be TDB');
  if (value.timeOrigin !== 'J2000-ET') throw new EphemerisPackFormatError('timeOrigin must be J2000-ET');
  if (value.positionUnit !== 'm') throw new EphemerisPackFormatError('positionUnit must be m');
  if (value.timeUnit !== 's') throw new EphemerisPackFormatError('timeUnit must be s');

  const validStart = requireFiniteNumber(value.validStart, 'validStart');
  const validEnd = requireFiniteNumber(value.validEnd, 'validEnd');
  if (!(validStart < validEnd)) throw new EphemerisPackFormatError('validStart must be less than validEnd');

  if (!Array.isArray(value.series) || value.series.length === 0) {
    throw new EphemerisPackFormatError('series must be a non-empty array');
  }
  const series: EphemerisSeries[] = [];
  let expectedOffset = 0;
  for (let i = 0; i < value.series.length; i++) {
    const raw = value.series[i];
    if (!isRecord(raw)) throw new EphemerisPackFormatError(`series[${i}] must be an object`);
    const body = requireString(raw.body, `series[${i}].body`);
    const start = requireFiniteNumber(raw.start, `series[${i}].start`);
    const end = requireFiniteNumber(raw.end, `series[${i}].end`);
    if (!(start < end)) throw new EphemerisPackFormatError(`series[${i}] start must be less than end`);
    if (start < validStart || end > validEnd) {
      throw new EphemerisPackFormatError(`series[${i}] range is outside manifest validity range`);
    }
    const degree = requireNonNegativeInteger(raw.degree, `series[${i}].degree`);
    const coefficientOffset = requireNonNegativeInteger(raw.coefficientOffset, `series[${i}].coefficientOffset`);
    const coefficientCount = requireNonNegativeInteger(raw.coefficientCount, `series[${i}].coefficientCount`);
    const expectedCount = 3 * (degree + 1);
    if (coefficientCount !== expectedCount) {
      throw new EphemerisPackFormatError(`series[${i}] coefficientCount must be 3 * (degree + 1)`);
    }
    if (coefficientOffset !== expectedOffset) {
      throw new EphemerisPackFormatError(`series[${i}] coefficientOffset is not contiguous`);
    }
    expectedOffset += coefficientCount;
    series.push({ body, start, end, degree, coefficientOffset, coefficientCount });
  }

  for (let i = 0; i < series.length; i++) {
    for (let j = i + 1; j < series.length; j++) {
      const left = series[i];
      const right = series[j];
      if (left === undefined || right === undefined || left.body !== right.body) continue;
      if (left.start < right.end && right.start < left.end) {
        throw new EphemerisPackFormatError(`series[${i}] and series[${j}] overlap for body ${left.body}`);
      }
    }
  }

  const payloadSha256 = value.payloadSha256;
  if (payloadSha256 !== undefined &&
      (typeof payloadSha256 !== 'string' || !/^[0-9a-f]{64}$/.test(payloadSha256))) {
    throw new EphemerisPackFormatError('payloadSha256 must be 64 lowercase hexadecimal characters');
  }

  return { ...value, series } as unknown as EphemerisManifest;
}

/** Encode numbers independently of host endianness. */
export function encodeFloat64Payload(values: ArrayLike<number>): Uint8Array {
  const bytes = new Uint8Array(values.length * 8);
  const view = new DataView(bytes.buffer);
  for (let i = 0; i < values.length; i++) {
    const value = values[i];
    if (value === undefined || !Number.isFinite(value)) {
      throw new EphemerisPackFormatError(`payload[${i}] must be finite`);
    }
    view.setFloat64(i * 8, value, true);
  }
  return bytes;
}

/** Build the manifest offsets and flattened X/Y/Z payload from JSON-friendly segments. */
export function buildEphemerisPackData(
  manifestBase: EphemerisManifestBase,
  segments: readonly ChebyshevSegmentInput[],
): { readonly manifest: EphemerisManifest; readonly payload: Float64Array } {
  if (segments.length === 0) throw new EphemerisPackFormatError('at least one segment is required');
  const series: EphemerisSeries[] = [];
  const values: number[] = [];
  let coefficientOffset = 0;
  for (let i = 0; i < segments.length; i++) {
    const segment = segments[i];
    if (segment === undefined) throw new EphemerisPackFormatError(`segment[${i}] is missing`);
    const [x, y, z] = segment.coefficients;
    if (x.length === 0 || x.length !== y.length || x.length !== z.length) {
      throw new EphemerisPackFormatError(`segment[${i}] must have equally sized, non-empty XYZ coefficients`);
    }
    for (const coefficient of [...x, ...y, ...z]) {
      if (!Number.isFinite(coefficient)) throw new EphemerisPackFormatError(`segment[${i}] has a non-finite coefficient`);
    }
    const degree = x.length - 1;
    const coefficientCount = 3 * x.length;
    series.push({
      body: segment.body,
      start: segment.start,
      end: segment.end,
      degree,
      coefficientOffset,
      coefficientCount,
    });
    values.push(...x, ...y, ...z);
    coefficientOffset += coefficientCount;
  }
  const manifest = validateManifest({ ...manifestBase, series });
  return { manifest, payload: Float64Array.from(values) };
}

export function encodeEphemerisPack(manifestValue: unknown, payload: ArrayLike<number>): Uint8Array {
  const manifest = validateManifest(manifestValue);
  const expectedValues = manifest.series.reduce((sum, item) => sum + item.coefficientCount, 0);
  if (payload.length !== expectedValues) {
    throw new EphemerisPackFormatError(`payload has ${payload.length} values; expected ${expectedValues}`);
  }
  const manifestBytes = new TextEncoder().encode(canonicalJson(manifest));
  const payloadBytes = encodeFloat64Payload(payload);
  if (manifestBytes.length > 0xffffffff || payloadBytes.length > 0xffffffff) {
    throw new EphemerisPackFormatError('manifest or payload is too large for version 1');
  }
  const output = new Uint8Array(EPHEMERIS_PACK_HEADER_BYTES + manifestBytes.length + payloadBytes.length);
  const view = new DataView(output.buffer);
  for (let i = 0; i < EPHEMERIS_PACK_MAGIC.length; i++) output[i] = EPHEMERIS_PACK_MAGIC.charCodeAt(i);
  view.setUint16(8, EPHEMERIS_PACK_VERSION, true);
  view.setUint16(10, EPHEMERIS_PACK_MINOR_VERSION, true);
  view.setUint32(12, EPHEMERIS_PACK_HEADER_BYTES, true);
  view.setUint32(16, manifestBytes.length, true);
  view.setUint32(20, payloadBytes.length, true);
  output.set(manifestBytes, EPHEMERIS_PACK_HEADER_BYTES);
  output.set(payloadBytes, EPHEMERIS_PACK_HEADER_BYTES + manifestBytes.length);
  return output;
}

export function decodeEphemerisPack(input: Uint8Array): DecodedEphemerisPack {
  if (!(input instanceof Uint8Array) || input.length < EPHEMERIS_PACK_HEADER_BYTES) {
    throw new EphemerisPackFormatError('pack is shorter than its header');
  }
  const view = new DataView(input.buffer, input.byteOffset, input.byteLength);
  for (let i = 0; i < EPHEMERIS_PACK_MAGIC.length; i++) {
    if (input[i] !== EPHEMERIS_PACK_MAGIC.charCodeAt(i)) throw new EphemerisPackFormatError('bad pack magic');
  }
  if (view.getUint16(8, true) !== EPHEMERIS_PACK_VERSION || view.getUint16(10, true) !== EPHEMERIS_PACK_MINOR_VERSION) {
    throw new EphemerisPackFormatError('unsupported binary pack version');
  }
  if (view.getUint32(12, true) !== EPHEMERIS_PACK_HEADER_BYTES) throw new EphemerisPackFormatError('bad header size');
  if (view.getUint32(24, true) !== 0 || view.getUint32(28, true) !== 0) {
    throw new EphemerisPackFormatError('reserved header bytes must be zero');
  }
  const manifestLength = view.getUint32(16, true);
  const payloadLength = view.getUint32(20, true);
  const payloadStart = EPHEMERIS_PACK_HEADER_BYTES + manifestLength;
  if (payloadStart > input.length || payloadLength !== input.length - payloadStart) {
    throw new EphemerisPackFormatError('pack length does not match its header');
  }
  if (payloadLength % 8 !== 0) throw new EphemerisPackFormatError('payload length is not Float64-aligned');

  let manifestJson: string;
  try {
    manifestJson = new TextDecoder('utf-8', { fatal: true }).decode(input.subarray(EPHEMERIS_PACK_HEADER_BYTES, payloadStart));
  } catch {
    throw new EphemerisPackFormatError('manifest is not valid UTF-8');
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(manifestJson) as unknown;
  } catch {
    throw new EphemerisPackFormatError('manifest is not valid JSON');
  }
  const manifest = validateManifest(parsed);
  if (canonicalJson(manifest) !== manifestJson) throw new EphemerisPackFormatError('manifest is not canonical JSON');
  const expectedValues = manifest.series.reduce((sum, item) => sum + item.coefficientCount, 0);
  if (payloadLength !== expectedValues * 8) throw new EphemerisPackFormatError('payload length does not match manifest');

  const payloadBytes = input.slice(payloadStart);
  const payload = new Float64Array(expectedValues);
  const payloadView = new DataView(payloadBytes.buffer, payloadBytes.byteOffset, payloadBytes.byteLength);
  for (let i = 0; i < payload.length; i++) {
    const value = payloadView.getFloat64(i * 8, true);
    if (!Number.isFinite(value)) throw new EphemerisPackFormatError(`payload[${i}] is not finite`);
    payload[i] = value;
  }
  return { manifest, payload, payloadBytes, manifestJson };
}

/**
 * Adapt a decoded binary pack to the existing Chebyshev evaluator contract.
 * The adapter is intentionally explicit: evaluator times remain J2000-ET
 * seconds, while the binary manifest retains the authoritative ICRF/TDB
 * frame and epoch metadata.
 */
export function toEvaluatorEphemerisPack(decoded: DecodedEphemerisPack): CanonicalEvaluatorEphemerisPack {
  const bodies = new Map<string, {
    readonly id: string;
    readonly segments: Array<{
      readonly start: number;
      readonly end: number;
      readonly degree: number;
      readonly coefficients: [number[], number[], number[]];
    }>;
  }>();
  for (const series of decoded.manifest.series) {
    let body = bodies.get(series.body);
    if (body === undefined) {
      body = { id: series.body, segments: [] };
      bodies.set(series.body, body);
    }
    const componentLength = series.degree + 1;
    const offset = series.coefficientOffset;
    body.segments.push({
      start: series.start,
      end: series.end,
      degree: series.degree,
      coefficients: [
        Array.from(decoded.payload.slice(offset, offset + componentLength)),
        Array.from(decoded.payload.slice(offset + componentLength, offset + 2 * componentLength)),
        Array.from(decoded.payload.slice(offset + 2 * componentLength, offset + 3 * componentLength)),
      ],
    });
  }
  const bodyPacks = [...bodies.values()];
  return {
    manifest: {
      version: decoded.manifest.version,
      timeUnit: 's',
      positionUnit: 'm',
      coordinateFrame: 'ICRF-J2000',
      timeScale: 'TDB',
      bodies: bodyPacks.map((body) => ({
        id: body.id,
        segments: body.segments.map(({ start, end, degree }) => ({ start, end, degree })),
      })),
    },
    bodies: bodyPacks,
  } as unknown as CanonicalEvaluatorEphemerisPack;
}
