/**
 * Version 1 of the Tepui ephemeris pack format.
 *
 * The file is deliberately small and boring so it can be generated by a
 * dependency-free Node tool and consumed in a browser:
 *
 *   0..7    ASCII magic "TEPUIEPK"
 *   8..9    uint16 LE major version (1)
 *   10..11  uint16 LE minor version (0)
 *   12..15  uint32 LE header size (32)
 *   16..19  uint32 LE canonical manifest UTF-8 byte length
 *   20..23  uint32 LE payload byte length
 *   24..31  zero-filled reserved bytes
 *   ...     canonical JSON manifest, UTF-8
 *   ...     contiguous Float64 position coefficients, little endian
 *
 * A series stores X, then Y, then Z Chebyshev coefficients.  Thus a series
 * of degree n has 3 * (n + 1) Float64 values.  The manifest's
 * coefficientOffset is measured in Float64 values, not bytes.  Coefficients
 * are evaluated on each series' [start, end] interval with the usual affine
 * mapping to [-1, 1].  Times and positions are in the units declared by the
 * manifest. Version 1 uses barycentric ICRF/J2000 positions in metres and
 * times expressed as seconds from the J2000 ET epoch on the TDB scale.
 *
 * The wire key for one body's one interval is `series`; the word in code is
 * `segment` (`PackSegment`).  The wire spelling is frozen at version 1 — changing
 * it would force a major version bump, which invalidates every existing save
 * through `EphemerisContext.packFormatVersion`.
 *
 * The manifest is canonical JSON: object keys are sorted recursively, arrays
 * retain their order, and no insignificant whitespace is emitted.  The
 * payloadSha256 field, when present, is the lowercase SHA-256 digest of only
 * the payload bytes (not the header or manifest).  The browser-side format
 * code intentionally does not depend on a crypto implementation; the Node
 * CLI verifies this field.
 */

import type { EphemerisPointKind } from '../point-ephemeris';
import type { ChebyshevPack } from './types';

export const EPHEMERIS_PACK_MAGIC = 'TEPUIEPK';
export const EPHEMERIS_PACK_FORMAT = 'tepui-ephemeris-pack';
export const EPHEMERIS_PACK_VERSION = 1;
export const EPHEMERIS_PACK_MINOR_VERSION = 0;
export const EPHEMERIS_PACK_HEADER_BYTES = 32;

export interface PackSegment {
  readonly body: string;
  readonly start: number;
  readonly end: number;
  readonly degree: number;
  readonly coefficientOffset: number;
  readonly coefficientCount: number;
}

export interface PackManifest {
  readonly format: typeof EPHEMERIS_PACK_FORMAT;
  readonly version: typeof EPHEMERIS_PACK_VERSION;
  readonly frame: 'ICRF-J2000';
  readonly timeScale: 'TDB';
  /** validStart/end and series start/end are seconds from J2000 ET. */
  readonly timeOrigin: 'J2000-ET';
  readonly positionUnit: 'm';
  readonly timeUnit: 's';
  readonly validStart: number;
  readonly validEnd: number;
  readonly series: readonly PackSegment[];
  /** body ごとに収録している点。欠けている body は 'body'(天体そのものの中心)。 */
  readonly bodyPoints?: Readonly<Record<string, EphemerisPointKind>>;
  readonly payloadSha256?: string;
  readonly [key: string]: unknown;
}

export type PackManifestBase = Omit<PackManifest, 'series'>;

export interface ChebyshevSegmentInput {
  readonly body: string;
  readonly start: number;
  readonly end: number;
  /** [x coefficients, y coefficients, z coefficients]. */
  readonly coefficients: readonly [readonly number[], readonly number[], readonly number[]];
}

export interface DecodedPack {
  readonly manifest: PackManifest;
  readonly payload: Float64Array;
  /** The exact bytes hashed by manifest.payloadSha256. */
  readonly payloadBytes: Uint8Array;
  readonly manifestJson: string;
}

export class PackFormatError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = 'PackFormatError';
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function requireString(value: unknown, field: string): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new PackFormatError(`${field} must be a non-empty string`);
  }
  return value;
}

function requireFiniteNumber(value: unknown, field: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new PackFormatError(`${field} must be finite`);
  }
  return value;
}

function requireNonNegativeInteger(value: unknown, field: string): number {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) {
    throw new PackFormatError(`${field} must be a non-negative safe integer`);
  }
  return value;
}

/** Sort object keys recursively while preserving array order. */
export function canonicalJson(value: unknown): string {
  if (value === null || typeof value === 'boolean' || typeof value === 'string' || typeof value === 'number') {
    if (typeof value === 'number' && !Number.isFinite(value)) {
      throw new PackFormatError('manifest cannot contain a non-finite number');
    }
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalJson(item)).join(',')}]`;
  }
  if (!isRecord(value)) {
    throw new PackFormatError('manifest contains an unsupported JSON value');
  }
  const keys = Object.keys(value).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`;
}

/** Validate and return the manifest with its public shape narrowed. */
export function validateManifest(value: unknown): PackManifest {
  if (!isRecord(value)) throw new PackFormatError('manifest must be a JSON object');
  if (value.format !== EPHEMERIS_PACK_FORMAT) {
    throw new PackFormatError(`unsupported manifest format: ${String(value.format)}`);
  }
  if (value.version !== EPHEMERIS_PACK_VERSION) {
    throw new PackFormatError(`unsupported manifest version: ${String(value.version)}`);
  }
  if (value.frame !== 'ICRF-J2000') throw new PackFormatError('frame must be ICRF-J2000');
  if (value.timeScale !== 'TDB') throw new PackFormatError('timeScale must be TDB');
  if (value.timeOrigin !== 'J2000-ET') throw new PackFormatError('timeOrigin must be J2000-ET');
  if (value.positionUnit !== 'm') throw new PackFormatError('positionUnit must be m');
  if (value.timeUnit !== 's') throw new PackFormatError('timeUnit must be s');

  const validStart = requireFiniteNumber(value.validStart, 'validStart');
  const validEnd = requireFiniteNumber(value.validEnd, 'validEnd');
  if (!(validStart < validEnd)) throw new PackFormatError('validStart must be less than validEnd');

  if (!Array.isArray(value.series) || value.series.length === 0) {
    throw new PackFormatError('series must be a non-empty array');
  }
  const series: PackSegment[] = [];
  let expectedOffset = 0;
  for (let i = 0; i < value.series.length; i++) {
    const raw = value.series[i];
    if (!isRecord(raw)) throw new PackFormatError(`series[${i}] must be an object`);
    const body = requireString(raw.body, `series[${i}].body`);
    const start = requireFiniteNumber(raw.start, `series[${i}].start`);
    const end = requireFiniteNumber(raw.end, `series[${i}].end`);
    if (!(start < end)) throw new PackFormatError(`series[${i}] start must be less than end`);
    if (start < validStart || end > validEnd) {
      throw new PackFormatError(`series[${i}] range is outside manifest validity range`);
    }
    const degree = requireNonNegativeInteger(raw.degree, `series[${i}].degree`);
    const coefficientOffset = requireNonNegativeInteger(raw.coefficientOffset, `series[${i}].coefficientOffset`);
    const coefficientCount = requireNonNegativeInteger(raw.coefficientCount, `series[${i}].coefficientCount`);
    const expectedCount = 3 * (degree + 1);
    if (coefficientCount !== expectedCount) {
      throw new PackFormatError(`series[${i}] coefficientCount must be 3 * (degree + 1)`);
    }
    if (coefficientOffset !== expectedOffset) {
      throw new PackFormatError(`series[${i}] coefficientOffset is not contiguous`);
    }
    expectedOffset += coefficientCount;
    series.push({ body, start, end, degree, coefficientOffset, coefficientCount });
  }

  for (let i = 0; i < series.length; i++) {
    for (let j = i + 1; j < series.length; j++) {
      const left = series[i];
      const right = series[j];
      if (left === undefined || right === undefined || left.body !== right.body) continue;
      if (left.start < right.end && right.start < left.end) {
        throw new PackFormatError(`series[${i}] and series[${j}] overlap for body ${left.body}`);
      }
    }
  }

  const bodyPoints = value.bodyPoints;
  if (bodyPoints !== undefined) {
    if (!isRecord(bodyPoints)) throw new PackFormatError('bodyPoints must be a JSON object');
    for (const [body, kind] of Object.entries(bodyPoints)) {
      if (kind !== 'body' && kind !== 'systemBarycenter') {
        throw new PackFormatError(`bodyPoints[${body}] must be body or systemBarycenter`);
      }
    }
  }

  const payloadSha256 = value.payloadSha256;
  if (payloadSha256 !== undefined &&
      (typeof payloadSha256 !== 'string' || !/^[0-9a-f]{64}$/.test(payloadSha256))) {
    throw new PackFormatError('payloadSha256 must be 64 lowercase hexadecimal characters');
  }

  return { ...value, series } as unknown as PackManifest;
}

/** Encode numbers independently of host endianness. */
export function encodeFloat64Payload(values: ArrayLike<number>): Uint8Array {
  const bytes = new Uint8Array(values.length * 8);
  const view = new DataView(bytes.buffer);
  for (let i = 0; i < values.length; i++) {
    const value = values[i];
    if (value === undefined || !Number.isFinite(value)) {
      throw new PackFormatError(`payload[${i}] must be finite`);
    }
    view.setFloat64(i * 8, value, true);
  }
  return bytes;
}

/** Build the manifest offsets and flattened X/Y/Z payload from JSON-friendly segments. */
export function buildPackData(
  manifestBase: PackManifestBase,
  segments: readonly ChebyshevSegmentInput[],
): { readonly manifest: PackManifest; readonly payload: Float64Array } {
  if (segments.length === 0) throw new PackFormatError('at least one segment is required');
  const series: PackSegment[] = [];
  const values: number[] = [];
  let coefficientOffset = 0;
  for (let i = 0; i < segments.length; i++) {
    const segment = segments[i];
    if (segment === undefined) throw new PackFormatError(`segment[${i}] is missing`);
    const [x, y, z] = segment.coefficients;
    if (x.length === 0 || x.length !== y.length || x.length !== z.length) {
      throw new PackFormatError(`segment[${i}] must have equally sized, non-empty XYZ coefficients`);
    }
    for (const coefficient of [...x, ...y, ...z]) {
      if (!Number.isFinite(coefficient)) throw new PackFormatError(`segment[${i}] has a non-finite coefficient`);
    }
    const degree = x.length - 1;
    const coefficientCount = 3 * x.length;
    series.push({
      body: segment.body,
      start: segment.start,
      end: segment.end,
      degree,
      coefficientOffset,
      coefficientCount,
    });
    values.push(...x, ...y, ...z);
    coefficientOffset += coefficientCount;
  }
  const manifest = validateManifest({ ...manifestBase, series });
  return { manifest, payload: Float64Array.from(values) };
}

export function encodePack(manifestValue: unknown, payload: ArrayLike<number>): Uint8Array {
  const manifest = validateManifest(manifestValue);
  const expectedValues = manifest.series.reduce((sum, item) => sum + item.coefficientCount, 0);
  if (payload.length !== expectedValues) {
    throw new PackFormatError(`payload has ${payload.length} values; expected ${expectedValues}`);
  }
  const manifestBytes = new TextEncoder().encode(canonicalJson(manifest));
  const payloadBytes = encodeFloat64Payload(payload);
  if (manifestBytes.length > 0xffffffff || payloadBytes.length > 0xffffffff) {
    throw new PackFormatError('manifest or payload is too large for version 1');
  }
  const output = new Uint8Array(EPHEMERIS_PACK_HEADER_BYTES + manifestBytes.length + payloadBytes.length);
  const view = new DataView(output.buffer);
  for (let i = 0; i < EPHEMERIS_PACK_MAGIC.length; i++) output[i] = EPHEMERIS_PACK_MAGIC.charCodeAt(i);
  view.setUint16(8, EPHEMERIS_PACK_VERSION, true);
  view.setUint16(10, EPHEMERIS_PACK_MINOR_VERSION, true);
  view.setUint32(12, EPHEMERIS_PACK_HEADER_BYTES, true);
  view.setUint32(16, manifestBytes.length, true);
  view.setUint32(20, payloadBytes.length, true);
  output.set(manifestBytes, EPHEMERIS_PACK_HEADER_BYTES);
  output.set(payloadBytes, EPHEMERIS_PACK_HEADER_BYTES + manifestBytes.length);
  return output;
}

const HOST_IS_LITTLE_ENDIAN = new Uint8Array(Uint16Array.of(1).buffer)[0] === 1;

/**
 * Read `count` little-endian Float64 values out of `bytes`.
 * Throws PackFormatError if any value is non-finite.
 */
function decodeFloat64Payload(bytes: Uint8Array, count: number): Float64Array {
  const payload = new Float64Array(count);
  if (HOST_IS_LITTLE_ENDIAN) {
    // Float64Array の buffer は 8 バイト境界に揃うので、payload 側へ写してからビューを張る。
    new Uint8Array(payload.buffer).set(bytes);
  } else {
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    for (let i = 0; i < count; i++) payload[i] = view.getFloat64(i * 8, true);
  }
  for (let i = 0; i < count; i++) {
    if (!Number.isFinite(payload[i])) throw new PackFormatError(`payload[${i}] is not finite`);
  }
  return payload;
}

export function decodePack(input: Uint8Array): DecodedPack {
  if (!(input instanceof Uint8Array) || input.length < EPHEMERIS_PACK_HEADER_BYTES) {
    throw new PackFormatError('pack is shorter than its header');
  }
  const view = new DataView(input.buffer, input.byteOffset, input.byteLength);
  for (let i = 0; i < EPHEMERIS_PACK_MAGIC.length; i++) {
    if (input[i] !== EPHEMERIS_PACK_MAGIC.charCodeAt(i)) throw new PackFormatError('bad pack magic');
  }
  if (view.getUint16(8, true) !== EPHEMERIS_PACK_VERSION || view.getUint16(10, true) !== EPHEMERIS_PACK_MINOR_VERSION) {
    throw new PackFormatError('unsupported binary pack version');
  }
  if (view.getUint32(12, true) !== EPHEMERIS_PACK_HEADER_BYTES) throw new PackFormatError('bad header size');
  if (view.getUint32(24, true) !== 0 || view.getUint32(28, true) !== 0) {
    throw new PackFormatError('reserved header bytes must be zero');
  }
  const manifestLength = view.getUint32(16, true);
  const payloadLength = view.getUint32(20, true);
  const payloadStart = EPHEMERIS_PACK_HEADER_BYTES + manifestLength;
  if (payloadStart > input.length || payloadLength !== input.length - payloadStart) {
    throw new PackFormatError('pack length does not match its header');
  }
  if (payloadLength % 8 !== 0) throw new PackFormatError('payload length is not Float64-aligned');

  let manifestJson: string;
  try {
    manifestJson = new TextDecoder('utf-8', { fatal: true }).decode(input.subarray(EPHEMERIS_PACK_HEADER_BYTES, payloadStart));
  } catch {
    throw new PackFormatError('manifest is not valid UTF-8');
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(manifestJson) as unknown;
  } catch {
    throw new PackFormatError('manifest is not valid JSON');
  }
  const manifest = validateManifest(parsed);
  if (canonicalJson(manifest) !== manifestJson) throw new PackFormatError('manifest is not canonical JSON');
  const expectedValues = manifest.series.reduce((sum, item) => sum + item.coefficientCount, 0);
  if (payloadLength !== expectedValues * 8) throw new PackFormatError('payload length does not match manifest');

  const payloadBytes = input.subarray(payloadStart);
  const payload = decodeFloat64Payload(payloadBytes, expectedValues);
  return { manifest, payload, payloadBytes, manifestJson };
}

// 復号済みの pack を評価器の入力へ写す。timeOriginSec を渡すと、セグメント境界をその原点
// からの秒へ寄せる — 評価器はワイヤ形式の J2000 ET 秒を知らずに済み、呼び出し側が決めた
// 時刻軸だけで引ける。**manifest 側と bodies 側は同じ segments から組むので、片方だけが
// ずれることはない**(評価器の検証はこの一致を要求する)。
// **係数は複製せず decoded.payload へのビューとして返す** — 返り値が生きているあいだ
// payload も生き続ける。呼び出し側は payload を書き換えてはならない。
export function toChebyshevPack(
  decoded: DecodedPack, timeOriginSec = 0,
): ChebyshevPack {
  const bodies = new Map<string, {
    readonly id: string;
    readonly segments: Array<{
      readonly start: number;
      readonly end: number;
      readonly degree: number;
      readonly coefficients: [Float64Array, Float64Array, Float64Array];
    }>;
  }>();
  for (const series of decoded.manifest.series) {
    let body = bodies.get(series.body);
    if (body === undefined) {
      body = { id: series.body, segments: [] };
      bodies.set(series.body, body);
    }
    const componentLength = series.degree + 1;
    const offset = series.coefficientOffset;
    body.segments.push({
      start: series.start - timeOriginSec,
      end: series.end - timeOriginSec,
      degree: series.degree,
      // **係数はコピーせず payload へのビューで持つ。** coefficientOffset は Float64 の
      // 要素単位なので subarray は常に 8 バイト境界に揃う(decodeFloat64Payload が確保する
      // Float64Array がそもそも揃っている)。復号した payload をこの pack が生かし続ける。
      coefficients: [
        decoded.payload.subarray(offset, offset + componentLength),
        decoded.payload.subarray(offset + componentLength, offset + 2 * componentLength),
        decoded.payload.subarray(offset + 2 * componentLength, offset + 3 * componentLength),
      ],
    });
  }
  const bodyPacks = [...bodies.values()];
  return {
    manifest: {
      version: decoded.manifest.version,
      timeUnit: 's',
      positionUnit: 'm',
      bodies: bodyPacks.map((body) => ({
        id: body.id,
        segments: body.segments.map(({ start, end, degree }) => ({ start, end, degree })),
      })),
    },
    bodies: bodyPacks,
  };
}
