// 地表配信物のランタイムwire契約。manifestとESTN/ESTBの検証・decodeが共有する。

export const EARTH_SURFACE_MANIFEST_SCHEMA_VERSION = 3;
export const EARTH_SURFACE_TERRAIN_FORMAT_VERSION = 3;
export const EARTH_TERRAIN_HEADER_BYTES = 32;
export const EARTH_TERRAIN_WIDTH = 260;
export const EARTH_TERRAIN_HEIGHT = 260;
export const EARTH_TERRAIN_CHANNELS = 4;
export const EARTH_TERRAIN_SCALAR_UINT8 = 2;
export const EARTH_TERRAIN_BYTES = EARTH_TERRAIN_WIDTH * EARTH_TERRAIN_HEIGHT * EARTH_TERRAIN_CHANNELS;
export const EARTH_TERRAIN_LAYOUT = 'normal-xyz-rgb8-roughness-a8';
