// DOM/THREE 非依存のゲームロジックの回帰テスト エントリポイント。
// `npm run test:unit` から tsconfig.test.json でコンパイル後、これを node 実行する。
import { runAll } from '../physics/harness';
import { register as registerAttitudeControl } from './attitude-control.test';
import { register as registerBlueprint } from './blueprint-validation.test';
import { register as registerCapabilities } from './capabilities.test';
import { register as registerBlueprintBudgets } from './blueprint-validation-budgets.test';
import { register as registerMember } from './member.test';
import { register as registerCommCoverage, registerInitialCoverage } from './comm-coverage.test';
import { register as registerHeatShield } from './heat-shield.test';
import { register as registerHullMesh } from './hull-mesh.test';
import { register as registerMassProperties } from './mass-properties.test';
import { register as registerProducibility } from './producibility.test';
import { register as registerProduction } from './production.test';
import { register as registerResource } from './resource.test';
import { register as registerResourceClosure } from './resource-closure.test';
import { register as registerVesselParts } from './vessel-parts.test';
import { register as registerMining } from './mining.test';
import { register as registerLanding } from './landing.test';
import { register as registerDockWorkbench } from './dock-workbench.test';
import { register as registerLunarBase } from './lunar-base.test';
import { register as registerDockingCapture } from './docking-capture.test';
import { register as registerStages } from './stages.test';
import { register as registerPayload } from './payload.test';
import { register as registerModulePick } from './module-pick.test';
import { register as registerAdvancedVessel } from './advanced-vessel.test';
import { register as registerDockingCluster } from './docking-cluster.test';
import { register as registerAssemblyEditor } from './assembly-editor.test';
import { register as registerBaseSave } from './base-save.test';
import { register as registerBaseGeometry } from './base-geometry.test';
import { register as registerMountCandidates } from './mount-candidates.test';

registerResource();
registerProducibility();
registerProduction();
registerResourceClosure();
registerCapabilities();
registerBlueprintBudgets();
registerMember();
registerVesselParts();
registerMining();
registerLanding();
registerDockWorkbench();
registerLunarBase();
registerDockingCapture();
registerStages();
registerPayload();
registerModulePick();
registerAdvancedVessel();
registerDockingCluster();
registerAssemblyEditor();
registerBaseSave();
registerBaseGeometry();
registerMountCandidates();
registerHullMesh();
registerMassProperties();
registerAttitudeControl();
registerHeatShield();
registerBlueprint();
registerCommCoverage();
registerInitialCoverage();

runAll().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
